@baseURL = http://127.0.0.1:5000

@identityAuthority = http://127.0.0.1:5000/login

@credential = {"username":"viewer","password":"viewerviewer"}

get {{baseURL}}

###

# @name login
post {{baseURL}}/login
Content-Type: application/json

{
    "username":"admin",
    "password":"adminadmin"
}


###

GET {{baseURL}}/user HTTP/1.1
Authorization: Bearer {{login.response.body.token}}

###

PUT {{baseURL}}/user HTTP/1.1
Authorization: Bearer {{login.response.body.token}}

{
    "email":"viewer@gmail.com",
}

###

PUT {{baseURL}}/user/update-password HTTP/1.1
Authorization: Bearer {{login.response.body.token}}

{
    "currentPassword":"adminadmin",
    "newPassword":"Viewerviewer_1!",
    "confirmPassword":"Viewerviewer_1!"
}

#################### THREATS #######################################

###

GET {{baseURL}}/threats?filter=-1 HTTP/1.1
Authorization: Bearer {{login.response.body.token}}

###

GET {{baseURL}}/threats HTTP/1.1
Authorization: Bearer {{login.response.body.token}}

###

GET {{baseURL}}/threats/0 HTTP/1.1
Authorization: Bearer {{login.response.body.token}}

#####################  

GET {{baseURL}}/threats/0 HTTP/1.1
Authorization: Bearer {{login.response.body.token}}

################# MITRE ########################

GET {{baseURL}}/mitre/T1001.001 HTTP/1.1
Authorization: Bearer {{login.response.body.token}}

################# CVE ########################

GET {{baseURL}}/cve/0 HTTP/1.1
Authorization: Bearer {{login.response.body.token}}